# -*- coding: utf-8 -*-
"""Examen_03_Analisis_Espectro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRqhAd-nofP5dOxUP9GLPcb6wmLmDTME

# **Limpieza de datos Examen 3**

# CARGA DE DATOS

**Conexión con Drive**
"""

from google.colab import drive
drive.mount('/content/drive')

"""**Importar las librerías**"""

import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt # gráfica
import glob # para buscar múltiples archivos
import os
from scipy import stats

"""**Leer y unificar los archivos .txt**"""

import glob
import os
import pandas as pd

ruta_carpeta = '/content/drive/MyDrive/IoT/examen3_medidas/'

# Encontrar todos los archivos .txt en la carpeta
archivos_txt = glob.glob(os.path.join(ruta_carpeta, "[0-9][0-9][0-9].txt"))

# Ordenar la lista de archivos alfabéticamente (y numéricamente por defecto)
archivos_txt = sorted(archivos_txt)

print(f"Cantidad de archivos encontrados: {len(archivos_txt)}")
print(archivos_txt[:5]) # Aquí confirmarás que inicia en 001.txt, 002.txt...

# Lista para guardar cada dataframe temporal
lista_dfs = []

# Bucle para leer cada archivo y agregarlo a la lista
for archivo in archivos_txt:
    df_temp = pd.read_csv(archivo, sep=',', header=None)
    lista_dfs.append(df_temp)

# Concatenar todos los DataFrames de la lista en uno solo
data = pd.concat(lista_dfs, ignore_index=True)

"""# ESTRUCTURA DEL DATASET"""

# Ver las primeras filas del nuevo dataset unificado
data.head()

# Revisar la cantidad de registros, columnas y tipos de datos
data.info()

# Nombrar las columnas

nombres_espectro = [f"freq_{i}" for i in range(1024)]

nombres_metadata = [
    "temperatura",
    "longitud",
    "latitud",
    "altura",
    "error_distancia"
]

nombres_columnas = nombres_espectro + nombres_metadata

data.columns = nombres_columnas

data.head()

"""**Separar espectro y metadatos**"""

espectro = data.iloc[:, :1024].copy()

metadata = data.iloc[:, 1024:].copy()

print("Espectro:", espectro.shape)
print("Metadata:", metadata.shape)

# Verificar que haya quedado bien divido el dataframe
metadata.head()

"""# REPORTE DE CALIDAD

**Verificación de nulos en los datos**
"""

# Conteo general de valores nulos en el dataset
print("Nulos totales:", data.isnull().sum().sum())

# Estadísticas descriptivas para detectar anomalías en coordenadas o temperatura
data[nombres_metadata].describe()

print("Dimensiones del dataset:")
print(data.shape)

print("\nTipos de datos:")
print(data.dtypes.value_counts())

print("\nValores nulos:")
print(data.isnull().sum().sum())

print("\nValores duplicados:")
print(data.duplicated().sum())

"""**Detección de mediciones espectrales atípicas**"""

# Análisis exploratorio de valores atípicos en los registros espectrales
import seaborn as sns

# Graficar el comportamiento de las 61 mediciones
plt.figure(figsize=(15, 6))
sns.boxplot(data=espectro.T) # DataFrame con las 61 columnas
plt.title("Distribución de Potencia de Espectro por Medición")
plt.xlabel("Número de Medición")
plt.ylabel("Potencia (dBm)")
plt.axhline(-5, color='r', linestyle='--', label='Referencia de revisión (-5 dBm)')
plt.legend()
plt.show()

"""El valor del registro 16 podría ser un atípico"""

# Análisis específico del registro 16
plt.figure(figsize=(14, 5))

for i in range(len(espectro)):
    if i == 15:
        plt.plot(espectro.iloc[i], linewidth=2.5, label='Medición 16')
    else:
        plt.plot(espectro.iloc[i], alpha=0.15)

plt.title('Comparación de las mediciones espectrales')
plt.xlabel('Bin de frecuencia')
plt.ylabel('Potencia (dBm)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

"""Se identificó que la medición 16 presenta un comportamiento atípico, caracterizado por un nivel de potencia elevado, incremento en el piso de ruido y un perfil espectral diferenciado. No obstante, al no presentar fallas de estructura, valores nulos ni inconsistencias en los metadatos, se conserva en el dataset como una observación válida. Las condiciones del entorno en mediciones móviles pueden generar estas variaciones, por lo que el registro se mantendrá sin imputar para evaluar posibles interferencias externas durante el análisis espacial.

**Identificación de errores en GPS y Metadata**
"""

# Identificar coordenadas inválidas (0 o nulas)
mask_metadata_posicional_invalida = (
    (metadata['latitud'] == 0) |
    (metadata['longitud'] == 0) |
    (metadata['altura'] == 0) |
    (metadata['latitud'].isnull()) |
    (metadata['longitud'].isnull()) |
    (metadata['altura'].isnull())
)

num_metadata_invalidos = mask_metadata_posicional_invalida.sum()
porcentaje_metadata_invalidos = (num_metadata_invalidos / len(metadata)) * 100

print(f"=== REPORTE INICIAL DE CALIDAD DE DATOS ===")
print(f"Total de registros: {len(metadata)}")
print(f"Registros con GPS en cero/inválido: {num_metadata_invalidos} ({porcentaje_metadata_invalidos:.2f}%)")

# Análisis de los valores vecinos al dato atípico
indice_invalido = metadata.index[mask_metadata_posicional_invalida][0]

print("Índice del registro inválido:", indice_invalido)

print("\nRegistros vecinos:")
print(
    metadata.loc[
        max(0, indice_invalido - 2):
        min(len(metadata), indice_invalido + 3)
    ]
)

"""**Revisar la matriz espectro**"""

# Verificación de valores no numéricos (NaN, Inf, -Inf)
nulos_espectro = espectro.isnull().sum().sum()
inf_positivos = np.isinf(espectro).sum().sum()
inf_negativos = np.isneginf(espectro).sum().sum()

print("=== REPORTE DE INTEGRIDAD FÍSICA DEL ESPECTRO ===")
print(f"Valores Nulos (NaN): {nulos_espectro}")
print(f"Valores Infinito (+Inf): {inf_positivos}")
print(f"Valores Infinito Negativo (-Inf): {inf_negativos}")

# Análisis de rangos físicos y outliers de potencia (dBm)
p_min = espectro.min().min()
p_max = espectro.max().max()
p_mean = espectro.values.mean()

print("\n=== ESTADÍSTICAS GLOBALES DE POTENCIA (dBm) ===")
print(f"Potencia Mínima Registrada: {p_min:.2f} dBm")
print(f"Potencia Máxima Registrada: {p_max:.2f} dBm")
print(f"Potencia Promedio del Espectro: {p_mean:.2f} dBm")

# Identificar mediciones atípicas/inconsistentes
# Se definen  0 dBm y -140 dBm como valores extremos
saturados = (espectro > 0).sum().sum()
lecturas_invalidas = (espectro < -140).sum().sum()

print(f"\nMuestras saturadas (> 0 dBm): {saturados}")
print(f"Muestras por debajo del límite físico de ruido (< -140 dBm): {lecturas_invalidas}")

"""**Revisar el error de distancia**"""

print("=== ANÁLISIS DEL ERROR DE DISTANCIA ===")

print(metadata['error_distancia'].describe())

print("\nValores de error de distancia ordenados:")
print(metadata['error_distancia'].sort_values().to_list())

plt.figure(figsize=(8, 4))

plt.boxplot(metadata['error_distancia'])

plt.ylabel('Error de distancia')
plt.title('Distribución del error de distancia')
plt.grid(alpha=0.3)

plt.show()

# Visualización del dato que tiene un error tan alto
print(metadata[metadata['error_distancia'] == 17.3])

# Visualización de los datos anterior y posterior para comparar metadata
print(metadata.loc[15:17])

"""Aunque la variable error_distancia presenta un pico estadísticamente atípico de 17.3, la inspección de las coordenadas confirma que no hubo pérdida de ubicación ni congelamiento de datos. La latitud y longitud registradas mantienen una progresión espacial coherente y contigua con el registro posterior (índice 17). Este aumento en el error de distancia podría indicar una disminución temporal en la precisión de la señal satelital, pero no constituye un dato corrupto, por lo que el registro se conserva intacto sin necesidad de aplicar métodos de imputación.

# CORRECCIÓN E IMPUTACIÓN

**Imputación del valor atípico**
"""

# Copia de la metadata original
metadata_imputada = metadata.copy()

# Convertir valores inválidos en NaN
metadata_imputada['latitud'] = metadata_imputada['latitud'].replace(0, np.nan)
metadata_imputada['longitud'] = metadata_imputada['longitud'].replace(0, np.nan)
metadata_imputada['altura'] = metadata_imputada['altura'].replace(0, np.nan)

# Mostrar el registro antes de interpolar
print("Registro 7 antes de la imputación:")
print(metadata_imputada.loc[7])

# Interpolación lineal según el orden de las mediciones
metadata_imputada['latitud'] = metadata_imputada['latitud'].interpolate(method='linear')
metadata_imputada['longitud'] = metadata_imputada['longitud'].interpolate(method='linear')
metadata_imputada['altura'] = metadata_imputada['altura'].interpolate(method='linear')

print("Registro 7 después de la imputación:")
print(metadata_imputada.loc[7])

# Comparar original vs. imputado
comparacion = pd.DataFrame({
    'Original': metadata.loc[7, ['longitud', 'latitud', 'altura']],
    'Imputado': metadata_imputada.loc[7, ['longitud', 'latitud', 'altura']]
})

print("=== COMPARACIÓN DEL REGISTRO IMPUTADO ===")
print(comparacion)

"""**Validación post-limpieza**"""

# Verificar que ya no quedan valores inválidos
print("\n=== VERIFICACIÓN POST-IMPUTACIÓN ===")

print(
    "Latitudes inválidas:",
    ((metadata_imputada['latitud'] == 0) |
     metadata_imputada['latitud'].isnull()).sum()
)

print(
    "Longitudes inválidas:",
    ((metadata_imputada['longitud'] == 0) |
     metadata_imputada['longitud'].isnull()).sum()
)

print(
    "Alturas inválidas:",
    ((metadata_imputada['altura'] == 0) |
     metadata_imputada['altura'].isnull()).sum()
)

"""**Se guarda el archivo limpio**"""

# Guardar el DataFrame con los metadatos imputados y las frecuencias limpias
data_procesada = pd.concat([espectro, metadata_imputada], axis=1)

# Exportar a CSV
data_procesada.to_csv("datos_mediciones_medellin_limpios.csv", index=False)

# Si deseas descargarlo directamente a tu máquina local desde Colab:
from google.colab import files

files.download("datos_mediciones_medellin_limpios.csv")

"""# RUTA DE LA ESTACIÓN

**Gráfica de la ruta de la estación móvil**
"""

plt.figure(figsize=(9, 6))

# Trazar la línea de la trayectoria recorrida
plt.plot(
    metadata_imputada['longitud'],
    metadata_imputada['latitud'],
    color='tab:blue',
    linestyle='-',
    linewidth=2,
    label='Ruta Recorrida'
)

# Destacar el punto de inicio (Salida)
plt.scatter(
    metadata_imputada['longitud'].iloc[0],
    metadata_imputada['latitud'].iloc[0],
    color='green',
    s=120,
    zorder=5,
    label='Inicio (Punto 1)'
)

# Destacar el punto final (Llegada)
plt.scatter(
    metadata_imputada['longitud'].iloc[-1],
    metadata_imputada['latitud'].iloc[-1],
    color='red',
    s=120,
    zorder=5,
    label='Fin (Punto 61)'
)

plt.title('Trayectoria de la Estación Móvil de Monitoreo (Occidente de Medellín)')
plt.xlabel('Longitud')
plt.ylabel('Latitud')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.tight_layout()
plt.show()

# Descripción técnica para el informe
print(f"Punto de Inicio: Lat {metadata_imputada['latitud'].iloc[0]:.5f}, Long {metadata_imputada['longitud'].iloc[0]:.5f}")
print(f"Punto Final:  Lat {metadata_imputada['latitud'].iloc[-1]:.5f}, Long {metadata_imputada['longitud'].iloc[-1]:.5f}")

"""# ANÁLISIS DE INCIDENCIA DE TEMPERATURA

**Análisis de temperatura y calidad**

Crear los indicadores de calidad
"""

calidad = pd.DataFrame(index=data.index)

# Temperatura del sensor
calidad['temperatura'] = metadata_imputada['temperatura']

# APLICACIÓN DE LA SUMATORIA DISCRETA DE PARSEVAL

# Conversión de dBm a mW (escala lineal)
espectro_mW = 10 ** (espectro / 10)

# Potencia media espectral mediante sumatoria discreta
# P_media = (1/N) * sum(P_k)
potencia_parseval_mW = (
    espectro_mW.sum(axis=1) / espectro_mW.shape[1]
)

# Conversión nuevamente a dBm
calidad['potencia_media'] = 10 * np.log10(potencia_parseval_mW)

# INDICADORES ADICIONALES DE CALIDAD
calidad['potencia_std'] = espectro.std(axis=1)
calidad['potencia_min'] = espectro.min(axis=1)
calidad['potencia_max'] = espectro.max(axis=1)

# Cantidad de bins que superan el umbral de -60 dBm
calidad['valores_ocupados'] = (espectro > -60).sum(axis=1)


# Porcentaje de ocupación
calidad['porcentaje_ocupacion'] = (
    calidad['valores_ocupados'] / espectro.shape[1]
) * 100

# Cantidad de bins menores a -65 dBm
calidad['valores_menores_65'] = (espectro < -65).sum(axis=1)

print("=== INDICADORES DE CALIDAD CALCULADOS CON PARSEVAL ===")
display(calidad.head())

"""Revisión de temperatura"""

print("\n=== DISTRIBUCIÓN DE TEMPERATURA ===")
print(f"Temperatura mínima: {calidad['temperatura'].min():.2f} °C")
print(f"Temperatura máxima: {calidad['temperatura'].max():.2f} °C")
print(f"Temperatura promedio: {calidad['temperatura'].mean():.2f} °C")
print(f"Desviación estándar: {calidad['temperatura'].std():.2f} °C")

# Gráfica de distribución
plt.figure(figsize=(9, 5))
plt.hist(calidad['temperatura'], bins=10, color='skyblue', edgecolor='black')
plt.xlabel('Temperatura del sensor (°C)')
plt.ylabel('Número de mediciones')
plt.title('Distribución de la temperatura del sensor')
plt.grid(alpha=0.3)
plt.show()

"""Correlación temperatura vs. indicadores de calidad"""

from scipy.stats import pearsonr, linregress

variables_calidad = [
    'potencia_media',
    'potencia_std',
    'potencia_min',
    'potencia_max',
    'valores_ocupados',
    'porcentaje_ocupacion',
    'valores_menores_65'
]

resultados_correlacion = []

for variable in variables_calidad:
    r, p = pearsonr(calidad['temperatura'], calidad[variable])
    resultados_correlacion.append({
        'Indicador': variable,
        'Correlación_r': r,
        'p_value': p
    })

resultados_correlacion = pd.DataFrame(resultados_correlacion)

print("\n=== MATRIZ DE CORRELACIÓN DE PEARSON ===")
display(resultados_correlacion)

"""Gráficas de relación"""

# Temperatura vs Potencia Media (Parseval)
plt.figure(figsize=(8, 5))
plt.scatter(calidad['temperatura'], calidad['potencia_media'], color='tab:blue', alpha=0.7)
plt.xlabel('Temperatura del sensor (°C)')
plt.ylabel('Potencia media espectral - Parseval (dBm)')
plt.title('Temperatura vs. Potencia Media Espectral')
plt.grid(alpha=0.3)
plt.show()

# Temperatura vs Variabilidad
plt.figure(figsize=(8, 5))
plt.scatter(calidad['temperatura'], calidad['potencia_std'], color='tab:orange', alpha=0.7)
plt.xlabel('Temperatura del sensor (°C)')
plt.ylabel('Desviación estándar (dB)')
plt.title('Temperatura vs. Variabilidad Espectral')
plt.grid(alpha=0.3)
plt.show()

# Temperatura vs Ocupación
plt.figure(figsize=(8, 5))
plt.scatter(calidad['temperatura'], calidad['porcentaje_ocupacion'], color='tab:green', alpha=0.7)
plt.xlabel('Temperatura del sensor (°C)')
plt.ylabel('Ocupación espectral (%)')
plt.title('Temperatura vs. Ocupación Espectral')
plt.grid(alpha=0.3)
plt.show()

"""Línea de tendencia"""

x = calidad['temperatura']
y = calidad['porcentaje_ocupacion']

pendiente, intercepto, r_value, p_value, std_err = linregress(x, y)
y_pred = intercepto + pendiente * x

plt.figure(figsize=(8, 5))
plt.scatter(x, y, label='Mediciones', color='tab:purple', alpha=0.7)
plt.plot(x, y_pred, label=f'Tendencia lineal (R²={r_value**2:.4f})', color='red', linestyle='--')

plt.xlabel('Temperatura del sensor (°C)')
plt.ylabel('Ocupación espectral (%)')
plt.title('Relación entre Temperatura y Ocupación Espectral')
plt.legend()
plt.grid(alpha=0.3)
plt.show()

print("\n=== RESULTADOS DE REGRESIÓN ===")
print(f"Pendiente: {pendiente:.4f}")
print(f"R² (Coef. determinación): {r_value**2:.4f}")
print(f"p-value: {p_value:.4f}")

"""**Evaluación de la Incidencia Térmica en los Datos:**

La temperatura presenta una asociación débil con algunos indicadores de las mediciones espectrales, pero no se observa evidencia suficiente para afirmar que sea un factor determinante de la calidad general de los resultados. En particular, se encontró una correlación positiva débil entre la temperatura y la desviación estándar de la potencia (r = 0.275, p = 0.032), así como una correlación negativa débil con la cantidad de valores inferiores a -65 dBm (r = -0.279, p = 0.030). Sin embargo, la relación con el porcentaje de ocupación fue débil y no estadísticamente significativa al nivel del 5% (r = 0.227, p = 0.078). De manera consistente, el modelo de regresión entre temperatura y porcentaje de ocupación presentó un R² de 0.0516 y un p-value de 0.0782, por lo que la temperatura explica aproximadamente el 5.16% de la variabilidad observada en este indicador y no se cuenta con evidencia estadística suficiente para establecer una relación lineal significativa.

Por tanto, la temperatura debe considerarse una variable de seguimiento en el control de calidad, pero los resultados obtenidos no permiten atribuirle una afectación significativa de las mediciones espectrales.

# **Análisis por Canales A, B, C y D**

**Segmentación y cálculo de Parseval por canal**
"""

# DEFINICIÓN DE LOS 4 CANALES
canales_indices = {
    'Canal_A (840-845 MHz)': (0, 256),
    'Canal_B (845-850 MHz)': (256, 512),
    'Canal_C (850-855 MHz)': (512, 768),
    'Canal_D (855-860 MHz)': (768, 1024)
}

# DataFrame para consolidar resultados
df_canales = pd.DataFrame(index=data.index)


# CÁLCULO POR CANAL
for nombre_canal, (inicio, fin) in canales_indices.items():

    # Extraer los bins correspondientes al canal
    bloque_canal = espectro.iloc[:, inicio:fin]

    # 1. Conversión dBm → mW
    bloque_mW = 10 ** (bloque_canal / 10)

    # 2. SUMATORIA DISCRETA DE PARSEVAL
    #    Potencia media del canal
    potencia_mW = (
        bloque_mW.sum(axis=1) / bloque_mW.shape[1]
    )

    # Conversión de mW → dBm
    nombre_corto = nombre_canal[:7]

    col_potencia = f'potencia_{nombre_corto}'

    df_canales[col_potencia] = (
        10 * np.log10(potencia_mW)
    )

    # 3. IDENTIFICACIÓN DE BINS OCUPADOS
    #    Umbral establecido por el examen: > -60 dBm
    bins_ocupados = (bloque_canal > -60).sum(axis=1)

    col_ocupados = f'bins_ocupados_{nombre_corto}'

    df_canales[col_ocupados] = bins_ocupados

    # 4. PORCENTAJE DE OCUPACIÓN DEL CANAL
    col_porcentaje = f'porcentaje_ocupacion_{nombre_corto}'

    df_canales[col_porcentaje] = (
        bins_ocupados / bloque_canal.shape[1]
    ) * 100


display(df_canales.head())

"""**Resumen ejecutivo para la ANE**"""

# RESUMEN EJECUTIVO PARA LA ANE
resumen_ane = []

for nombre_canal, (inicio, fin) in canales_indices.items():

    nombre_corto = nombre_canal[:7]

    col_p = f'potencia_{nombre_corto}'
    col_o = f'porcentaje_ocupacion_{nombre_corto}'

    # Potencia promedio del canal a través de todas las mediciones
    pot_promedio = df_canales[col_p].mean()

    # Mayor potencia registrada en el canal
    pot_max = df_canales[col_p].max()

    # Porcentaje promedio de ocupación del canal
    porcentaje_contaminado = df_canales[col_o].mean()

    resumen_ane.append({
        'Canal': nombre_canal,
        'Potencia Promedio Parseval (dBm)': round(pot_promedio, 2),
        'Potencia Máxima Registrada (dBm)': round(pot_max, 2),
        '% Ocupación Promedio (> -60 dBm)': round(porcentaje_contaminado, 2)
    })

df_resumen_ane = pd.DataFrame(resumen_ane)

print("\n=== REPORTE DE CONTAMINACIÓN POR CANAL (AGENCIA NACIONAL DEL ESPECTRO) ===")
display(df_resumen_ane)

# Identificar el canal con mayor y menor ocupación promedio
canal_mas_contaminado = (
    df_resumen_ane.loc[
        df_resumen_ane['% Ocupación Promedio (> -60 dBm)'].idxmax(),
        'Canal'
    ]
)

canal_menos_contaminado = (
    df_resumen_ane.loc[
        df_resumen_ane['% Ocupación Promedio (> -60 dBm)'].idxmin(),
        'Canal'
    ]
)

print(f"\n-> Canal con MAYOR ocupación: {canal_mas_contaminado}")
print(f"-> Canal con MENOR ocupación: {canal_menos_contaminado}")

"""**Gráfica comparativa de niveles de potencia**"""

plt.figure(figsize=(10, 6))

for nombre_canal in canales_indices.keys():
    col_p = f'potencia_{nombre_canal[:7]}'
    plt.plot(df_canales.index, df_canales[col_p], label=nombre_canal, marker='o', markersize=3, linestyle='-')

plt.axhline(y=-60, color='red', linestyle='--', linewidth=2, label='Umbral Contaminación ANE (-60 dBm)')
plt.title('Evolución Temporal de Potencia Media por Canal (Parseval)')
plt.xlabel('Índice de Muestra / Evento')
plt.ylabel('Potencia (dBm)')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""**Análisis de contaminación por canal:**

Los resultados muestran diferencias importantes en la ocupación espectral entre las cuatro bandas analizadas. El canal C (850–855 MHz) presenta los mayores niveles de potencia, con una potencia promedio de −46.50 dBm y una potencia máxima registrada de −11.33 dBm. Además, presenta porcentajes elevados de bins por encima del umbral de −60 dBm en múltiples mediciones, lo que indica una alta ocupación de esta banda.

Por otro lado, el canal A (840–845 MHz) presenta la menor potencia promedio, con −67.98 dBm, y menores niveles de ocupación respecto a los demás canales. Los canales B (845–850 MHz) y D (855–860 MHz) presentan un comportamiento intermedio.

En consecuencia, dentro del conjunto de mediciones analizado, la banda de 850–855 MHz es la que presenta mayor evidencia de ocupación espectral, mientras que la banda de 840–845 MHz presenta los menores niveles de ocupación. Estos resultados permiten identificar las bandas que requieren mayor atención en el análisis de planificación y uso del espectro.
"""

plt.figure(figsize=(10, 6))

# Canales específicos que queremos graficar
canales_a_graficar = ['Canal_A (840-845 MHz)', 'Canal_C (850-855 MHz)']

for nombre_canal in canales_a_graficar:
    col_p = f'potencia_{nombre_canal[:7]}'
    plt.plot(df_canales.index, df_canales[col_p], label=nombre_canal, marker='o', markersize=3, linestyle='-')

plt.axhline(y=-60, color='red', linestyle='--', linewidth=2, label='Umbral Contaminación ANE (-60 dBm)')
plt.title('Evolución Temporal de Potencia Media por Canal (Parseval) - Canal A y C')
plt.xlabel('Índice de Muestra / Evento')
plt.ylabel('Potencia (dBm)')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""**EXPORTACIÓN DE DATOS PARA DASHBOARD**"""

df_canales.info()

# Crear DataFrame con la información necesaria para React
datos_dashboard = pd.DataFrame({
    'medicion': range(1, len(data) + 1),

    # Ubicación
    'latitud': metadata_imputada['latitud'],
    'longitud': metadata_imputada['longitud'],
    'altura': metadata_imputada['altura'],

    # Variables del sensor
    'temperatura': metadata_imputada['temperatura'],
    'error_distancia': metadata_imputada['error_distancia'],

    # Canal A
    'potencia_A': df_canales['potencia_Canal_A'],
    'bins_ocupados_A': df_canales['bins_ocupados_Canal_A'],
    'ocupacion_A': df_canales['porcentaje_ocupacion_Canal_A'],

    # Canal B
    'potencia_B': df_canales['potencia_Canal_B'],
    'bins_ocupados_B': df_canales['bins_ocupados_Canal_B'],
    'ocupacion_B': df_canales['porcentaje_ocupacion_Canal_B'],

    # Canal C
    'potencia_C': df_canales['potencia_Canal_C'],
    'bins_ocupados_C': df_canales['bins_ocupados_Canal_C'],
    'ocupacion_C': df_canales['porcentaje_ocupacion_Canal_C'],

    # Canal D
    'potencia_D': df_canales['potencia_Canal_D'],
    'bins_ocupados_D': df_canales['bins_ocupados_Canal_D'],
    'ocupacion_D': df_canales['porcentaje_ocupacion_Canal_D']
})

# Canal más contaminado por medición
columnas_ocupacion = [
    'ocupacion_A',
    'ocupacion_B',
    'ocupacion_C',
    'ocupacion_D'
]

nombres_canales = {
    'ocupacion_A': 'A',
    'ocupacion_B': 'B',
    'ocupacion_C': 'C',
    'ocupacion_D': 'D'
}

datos_dashboard['canal_mas_contaminado'] = (
    datos_dashboard[columnas_ocupacion]
    .idxmax(axis=1)
    .map(nombres_canales)
)

datos_dashboard['ocupacion_maxima'] = (
    datos_dashboard[columnas_ocupacion]
    .max(axis=1)
)

# FRECUENCIA CONTAMINADA REPRESENTATIVA POR MEDICIÓN
# Criterio de contaminación: potencia > -60 dBm

frecuencias_mhz = np.linspace(
    840,
    860,
    1024,
    endpoint=False
)

espectro_valores = espectro.values

frecuencia_contaminada = []
potencia_contaminada = []

for fila in espectro_valores:

    # Bins que cumplen el criterio de contaminación
    indices_contaminados = np.where(fila > -60)[0]

    if len(indices_contaminados) == 0:
        # Si la medición no tiene ningún bin contaminado
        frecuencia_contaminada.append(np.nan)
        potencia_contaminada.append(np.nan)

    else:
        # Entre los bins contaminados,
        # seleccionar el de mayor potencia
        indice_local = indices_contaminados[
            np.argmax(fila[indices_contaminados])
        ]

        frecuencia_contaminada.append(
            frecuencias_mhz[indice_local]
        )

        potencia_contaminada.append(
            fila[indice_local]
        )

datos_dashboard[
    'frecuencia_contaminada_representativa_MHz'
] = frecuencia_contaminada

datos_dashboard[
    'potencia_frecuencia_contaminada_dBm'
] = potencia_contaminada


# FRECUENCIA MÁS CONTAMINADA DEL SISTEMA

# Identificar los bins que superan el umbral de -60 dBm
bins_contaminados = espectro_valores > -60

porcentaje_contaminacion_frecuencia = (
    bins_contaminados.mean(axis=0) * 100
)

indice_frecuencia_mas_contaminada = (
    porcentaje_contaminacion_frecuencia.argmax()
)

frecuencia_mas_contaminada_sistema = (
    frecuencias_mhz[indice_frecuencia_mas_contaminada]
)

porcentaje_mas_contaminada_sistema = (
    porcentaje_contaminacion_frecuencia[
        indice_frecuencia_mas_contaminada
    ]
)

print(
    f"Frecuencia más contaminada del sistema: "
    f"{frecuencia_mas_contaminada_sistema:.6f} MHz"
)

print(
    f"Presencia de contaminación: "
    f"{porcentaje_mas_contaminada_sistema:.2f}% "
    f"de las mediciones"
)

# Revisar resultado
display(datos_dashboard.head())

print(f"Registros exportados: {len(datos_dashboard)}")
print(f"Columnas exportadas: {len(datos_dashboard.columns)}")

# EXPORTAR JSON
ruta_json = '/content/mediciones_dashboard.json'

datos_dashboard.to_json(
    ruta_json,
    orient='records',
    indent=2,
    force_ascii=False
)

print(f"JSON generado correctamente: {ruta_json}")

files.download('/content/mediciones_dashboard.json')

